# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
